[build]
  command = "pip install -r requirements.txt && uvicorn src.langflow.api.main:app --host=0.0.0.0 --port=$PORT"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
