services:
  # Company Intelligence API Backend
  - type: web
    name: company-intelligence-api
    env: docker
    region: ohio
    plan: starter
    branch: main
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    numInstances: 1
    healthCheckPath: /api/health
    envVars:
      - key: ASTRA_DB_TOKEN
        sync: false
      - key: ASTRA_DB_ENDPOINT
        sync: false
      - key: LANGFLOW_API_KEY
        sync: false
      - key: LANGFLOW_FLOW_URL
        sync: false
      - key: EXA_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: DATA_FRESHNESS_DAYS
        value: "360"
      - key: LOG_LEVEL
        value: INFO
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://company-intelligence-frontend.onrender.com

  # Company Intelligence Frontend
  - type: web
    name: company-intelligence-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://company-intelligence-api.onrender.com/api
      - key: NODE_ENV
        value: production
